package org.example;

import com.google.protobuf.util.JsonFormat;
import ru.sovcombank.hackaton.proto.*;

import java.io.IOException;
import java.io.OutputStream;
import java.net.Socket;

public class Main {

    public static ExchangeInfoMessage exchangeInfoMessageHandshake = ExchangeInfoMessage.newBuilder()
            .setHeader(Header.newBuilder()
                    .setMessageNum("1")
                    .setTimestamp(System.currentTimeMillis())
                    .setSender("NotNullTestService")
                    .setReceiver("NotNullServer")
                    .build())

            .setRequest(Request.newBuilder()
                    .setCommand(MessageEnumsProto.CommandType.ctHandshake)
                    .addSupportedCommands(OwnCommand.newBuilder()
                            .setAlias("Идентификатор 1")
                            .setCaption("Заголовок 1")
                            .setDescription("Описание команды 1")
                            .addParameters(Parameter.newBuilder()
                                    .setAlias("Идентификатор команды 1")
                                    .setCaption("Заголовок команды 1")
                                    .setHint("Подсказка команды 1")
                                    .setValue(ValueRef.newBuilder()
                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .setFormat("формат данных")
                                            .build())
                                    .build())
                            .addParameters(Parameter.newBuilder()
                                    .setAlias("Идентификатор команды 2")
                                    .setCaption("Заголовок 2 команды")
                                    .setHint("Подсказка команды 2")
                                    .setValue(ValueRef.newBuilder()
                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .setFormat("формат данных")
                                            .build())
                                    .build())
                            .build())
                    .addSupportedCommands(OwnCommand.newBuilder()
                            .setAlias("Идентификатор 2")
                            .setCaption("Заголовок 2")
                            .setDescription("Описание команды 2")
                            .addParameters(Parameter.newBuilder()
                                    .setAlias("Идентификатор команды 1")
                                    .setCaption("Заголовок команды 1")
                                    .setHint("Подсказка команды 1")
                                    .setValue(ValueRef.newBuilder()
                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .setFormat("формат данных")
                                            .setValue("test value")
                                            .build())
                                    .build())
                            .addParameters(Parameter.newBuilder()
                                    .setAlias("Идентификатор команды 2")
                                    .setCaption("Заголовок 2 команды")
                                    .setHint("Подсказка команды 2")
                                    .setValue(ValueRef.newBuilder()

                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .setFormat("формат данных")
                                            .build())
                                    .build())
                            .build())
                    .build())
            .build();

    public static ExchangeInfoMessage exchangeInfoMessageStatus = ExchangeInfoMessage.newBuilder()
            .setHeader(Header.newBuilder()
                    .setMessageNum("1")
                    .setTimestamp(System.currentTimeMillis())
                    .setSender("NotNullTestService")
                    .setReceiver("NotNullServer")
                    .build())

            .setResponse(Response.newBuilder()
                    .setCommand(MessageEnumsProto.CommandType.ctStatus)
                    .setAnswerType(MessageEnumsProto.AnswerType.atAnswerOK)
                    .setStatus(Status.newBuilder()
                            .setAdvStatus(AdvInfo.newBuilder()
                                    .setCaption("Заголовок Родиона")
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("Идентифакатор поля Родиона")
                                            .setCaption("Заголовок поля Родиона")
                                            .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                            .build())
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("Идентификатор Родиона 2")
                                            .setCaption("Заголовок поля Родиона 2")
                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .build())
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("Идентификатор Родиона 3")
                                            .setCaption("Заголовок поля Родиона 3")
                                            .setDataType(MessageEnumsProto.DataType.dtInteger)
                                            .build())
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("Идентификатор Родиона 4")
                                            .setCaption("Заголовок поля Родиона 4")
                                            .setDataType(MessageEnumsProto.DataType.dtFloat)
                                            .build())
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("Идентификатор Родиона 5")
                                            .setCaption("Заголовок поля Родиона 5")
                                            .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                            .build())
                                    .setData(AdvInfoData.newBuilder()
                                            .setFullOrIncrement(true)
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("Идентификатор записи Родиона")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("Формат строкового представления Родиона")
                                                                    .setValue("Значение Родиона")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 2")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("Формат строкового представления Родиона 2")
                                                                    .setValue("Значение Родиона 2")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 3")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("Формат строкового представления Родиона 3")
                                                                    .setValue("Значение Родиона 3")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 4")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("Формат строкового представления Родиона 4")
                                                                    .setValue("Значение Родиона 4")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 5")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("Формат строкового представления Родиона 5")
                                                                    .setValue("Значение Родиона 5")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("Идентификатор записи Родиона 6")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 6")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("Формат строкового представления Родиона 6")
                                                                    .setValue("Значение Родиона 6")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 7")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("Формат строкового представления Родиона 7")
                                                                    .setValue("Значение Родиона 7")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 8")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("Формат строкового представления Родиона 8")
                                                                    .setValue("Значение Родиона 8")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 9")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("Формат строкового представления Родиона 9")
                                                                    .setValue("Значение Родиона 9")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 10")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("Формат строкового представления Родиона 10")
                                                                    .setValue("Значение Родиона 10")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("Идентификатор записи Родиона 11")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 11")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("Формат строкового представления Родиона 11")
                                                                    .setValue("Значение Родиона 11")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 12")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("Формат строкового представления Родиона 12")
                                                                    .setValue("Значение Родиона 12")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 13")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("Формат строкового представления Родиона 13")
                                                                    .setValue("Значение Родиона 13")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 14")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("Формат строкового представления Родиона 14")
                                                                    .setValue("Значение Родиона 14")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 15")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("Формат строкового представления Родиона 15")
                                                                    .setValue("Значение Родиона 15")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("Идентификатор записи Родиона 16")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 16")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("Формат строкового представления Родиона 16")
                                                                    .setValue("Значение Родиона 16")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 17")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("Формат строкового представления Родиона 17")
                                                                    .setValue("Значение Родиона 17")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 18")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("Формат строкового представления Родиона 18")
                                                                    .setValue("Значение Родиона 18")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 19")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("Формат строкового представления Родиона 19")
                                                                    .setValue("Значение Родиона 19")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 20")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("Формат строкового представления Родиона 20")
                                                                    .setValue("Значение Родиона 20")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("Идентификатор записи Родиона 21")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 21")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("Формат строкового представления Родиона 21")
                                                                    .setValue("Значение Родиона 21")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 22")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("Формат строкового представления Родиона 22")
                                                                    .setValue("Значение Родиона 22")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 23")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("Формат строкового представления Родиона 23")
                                                                    .setValue("Значение Родиона 23")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 24")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("Формат строкового представления Родиона 24")
                                                                    .setValue("Значение Родиона 24")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("Идентификатор поля для которого устанавливается значение Родиона 25")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("Формат строкового представления Родиона 25")
                                                                    .setValue("Значение Родиона 25")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .build())
                                    .build())
                            .build())
                    .build())
            .build();

    public static void main(String[] args) throws IOException, InterruptedException {
        Socket socket = new Socket("localhost", 8888);
        OutputStream out = socket.getOutputStream();
        byte[] data = exchangeInfoMessageHandshake.toByteArray();
        out.write(data);
        out.flush();
        //Thread.sleep(10000);

        byte[] dataStatus = exchangeInfoMessageStatus.toByteArray();
        out.write(dataStatus);
        out.flush();
        Thread.sleep(10000);
        socket.close();//
    }
}