package org.example;


import com.google.protobuf.MessageOrBuilder;
import com.google.protobuf.util.JsonFormat;
import ru.sovcombank.hackaton.proto.*;

import java.io.IOException;
import java.io.OutputStream;
import java.net.Socket;

public class NewMain {

    public static ExchangeInfoMessage exchangeInfoMessageHandshake = ExchangeInfoMessage.newBuilder()
            .setHeader(Header.newBuilder()
                    .setMessageNum("1")
                    .setTimestamp(System.currentTimeMillis())
                    .setSender("NotNullTestService")
                    .setReceiver("NotNullServer")
                    .build())

            .setRequest(Request.newBuilder()
                    .setCommand(MessageEnumsProto.CommandType.ctHandshake)
                    .addSupportedCommands(OwnCommand.newBuilder()
                            .setAlias("Идентификатор 1")
                            .setCaption("Заголовок 1")
                            .setDescription("Описание команды 1")
                            .addParameters(Parameter.newBuilder()
                                    .setAlias("Идентификатор команды 1")
                                    .setCaption("Заголовок команды 1")
                                    .setHint("Подсказка команды 1")
                                    .setValue(ValueRef.newBuilder()
                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .setFormat("формат данных")
                                            .build())
                                    .build())
                            .addParameters(Parameter.newBuilder()
                                    .setAlias("Идентификатор команды 2")
                                    .setCaption("Заголовок 2 команды")
                                    .setHint("Подсказка команды 2")
                                    .setValue(ValueRef.newBuilder()
                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .setFormat("формат данных")
                                            .build())
                                    .build())
                            .build())
                    .addSupportedCommands(OwnCommand.newBuilder()
                            .setAlias("Идентификатор 2")
                            .setCaption("Заголовок 2")
                            .setDescription("Описание команды 2")
                            .addParameters(Parameter.newBuilder()
                                    .setAlias("Идентификатор команды 1")
                                    .setCaption("Заголовок команды 1")
                                    .setHint("Подсказка команды 1")
                                    .setValue(ValueRef.newBuilder()
                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .setFormat("формат данных")
                                            .setValue("test value")
                                            .build())
                                    .build())
                            .addParameters(Parameter.newBuilder()
                                    .setAlias("Идентификатор команды 2")
                                    .setCaption("Заголовок 2 команды")
                                    .setHint("Подсказка команды 2")
                                    .setValue(ValueRef.newBuilder()

                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .setFormat("формат данных")
                                            .build())
                                    .build())
                            .build())
                    .build())
            .build();

    public static  ExchangeInfoMessage exchangeInfoMessageStatus = ExchangeInfoMessage.newBuilder()
            .setHeader(Header.newBuilder()
                    .setMessageNum("1")
                    .setTimestamp(System.currentTimeMillis())
                    .setSender("NotNullTestService")
                    .setReceiver("NotNullServer")
                    .build())

            .setResponse(Response.newBuilder()
                    .setCommand(MessageEnumsProto.CommandType.ctExecCommand)
                    .setAnswerType(MessageEnumsProto.AnswerType.atAnswerOK)
                    .setStatus(Status.newBuilder()
                            .setAdvStatus(AdvInfo.newBuilder()
                                    .setCaption("Заголовок Родиона")
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("1")
                                            .setCaption("Заголовок поля Родиона")
                                            .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                            .build())
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("2")
                                            .setCaption("Заголовок поля Родиона 2")
                                            .setDataType(MessageEnumsProto.DataType.dtString)
                                            .build())
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("3")
                                            .setCaption("Заголовок поля Родиона 3")
                                            .setDataType(MessageEnumsProto.DataType.dtInteger)
                                            .build())
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("4")
                                            .setCaption("Заголовок поля Родиона 4")
                                            .setDataType(MessageEnumsProto.DataType.dtFloat)
                                            .build())
                                    .addFields(AdvInfoFieldRef.newBuilder()
                                            .setAlias("5")
                                            .setCaption("Заголовок поля Родиона 5")
                                            .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                            .build())
                                    .setData(AdvInfoData.newBuilder()
                                            .setFullOrIncrement(true)
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("1")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("1")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("boolean")
                                                                    .setValue("true")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("2")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("text")
                                                                    .setValue("Значение Родиона 2")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("3")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("number")
                                                                    .setValue("3")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("4")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("number")
                                                                    .setValue("4,5")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("5")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("date")
                                                                    .setValue("2022-12-05")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("2")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("2")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("boolean")
                                                                    .setValue("false")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("3")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("text")
                                                                    .setValue("Значение Родиона 7")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("4")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("number")
                                                                    .setValue("8")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("5")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("number")
                                                                    .setValue("9")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("1")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("date")
                                                                    .setValue("2022-11-04")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("3")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("3")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("boolean")
                                                                    .setValue("false")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("4")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("text")
                                                                    .setValue("Значение Родиона 12")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("5")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("number")
                                                                    .setValue("13")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("1")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("number")
                                                                    .setValue("14")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("2")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("date")
                                                                    .setValue("2022-15-05")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("4")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("4")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("boolean")
                                                                    .setValue("false")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("5")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("text")
                                                                    .setValue("Значение Родиона 17")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("1")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("number")
                                                                    .setValue("18")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("2")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("number")
                                                                    .setValue("19")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("3")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("date")
                                                                    .setValue("2021-10-03")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .addRows(DataRow.newBuilder()
                                                    .setRowIdent("5")
                                                    .setIncrementDelete(true)
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("5")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtBoolean)
                                                                    .setFormat("boolean")
                                                                    .setValue("true")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("4")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtString)
                                                                    .setFormat("text")
                                                                    .setValue("Значение Родиона 22")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("3")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtInteger)
                                                                    .setFormat("number")
                                                                    .setValue("23")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("2")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtFloat)
                                                                    .setFormat("number")
                                                                    .setValue("24")
                                                                    .build())
                                                            .build())
                                                    .addValues(DataFieldValue.newBuilder()
                                                            .setAlias("1")
                                                            .setValue(ValueRef.newBuilder()
                                                                    .setDataType(MessageEnumsProto.DataType.dtDateTime)
                                                                    .setFormat("date")
                                                                    .setValue("2012-12-12")
                                                                    .build())
                                                            .build())
                                                    .build())
                                            .build())
                                    .build())
                            .build())
                    .build())
            .build();

    public static void main(String[] args) throws IOException, InterruptedException {
        Socket socket = new Socket("localhost", 8888);
        OutputStream out = socket.getOutputStream();
        byte[] data = exchangeInfoMessageHandshake.toByteArray();
        out.write(data);
        out.flush();
        //Thread.sleep(10000);

        System.out.println(toJson(exchangeInfoMessageStatus));
        byte[] dataStatus = exchangeInfoMessageStatus.toByteArray();
        out.write(dataStatus);
        out.flush();
        Thread.sleep(10000);
        socket.close();//
    }
    public static String toJson(MessageOrBuilder messageOrBuilder) throws IOException {
        return JsonFormat.printer().includingDefaultValueFields().print(messageOrBuilder);
    }
}
